"""learning mode changes

Revision ID: be3ed4a2763f
Revises: e1c6bc9f6340
Create Date: 2025-02-01 14:23:48.980292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be3ed4a2763f'
down_revision = 'e1c6bc9f6340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('watering_amount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('watering_frequency', sa.Interval(), nullable=True))
        batch_op.drop_column('watering_schedule')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('watering_schedule', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.drop_column('watering_frequency')
        batch_op.drop_column('watering_amount')

    # ### end Alembic commands ###
